version: "3.1"

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_PORT: 3308
      PMA_HOST: mysql
      MYSQL_USERNAME: "user"
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  db_data:
